AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notifier

  Sample SAM Template for notifier

Globals:
  Function:
    Timeout: 3

Resources:
  ReleaseEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: release.handler
      Runtime: python3.7
      Events:
        ReleaseEvent:
          Type: Api
          Properties:
            Path: /release
            Method: post

Outputs:
  ReleaseEventApi:
    Description: "API Gateway endpoint URL for Prod stage for Release Event function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/release/"
